### ISSUE TITLE
Should output Chinese number when run 書之

### ISSUE THREAD

**Issue by cuixiping** [antfu/wenyan-lang-vscode#12]
```
夫一夫二書之
```
Online IDE output:  一二
VSCode run output: 1  2

**Comment by antfu** [comment]
Will added. Currently, Online IDE hijacks the console.log to achieve that (and there are some cases, for example array of numbers, will not output properly in the online IDE. I would try to open a discussion about how we can improve and reuse these logics in the original repo. Thanks for bringing this up!

**Comment by antfu** [comment]
It's landed for a while. Closing for now. If you got any questions, feel free to raise up. Thanks!
