### ISSUE TITLE
prefix 中的中文可用吗？

### ISSUE THREAD

**Issue by nobodxbodon** [antfu/wenyan-lang-vscode#16]
比如：
```javascript
    "prefix": [
      "if",
      "若"
    ],
```
本地测试时，if 可以激活弹窗，但”若“好像不能。

**Comment by antfu** [comment]
Sorry, this seems not being support by VS Code. I was just adding them for testing the possibility. Please use the alphabet to trigger the snippet for now.

**Comment by nobodxbodon** [comment]
Thanks for confirming. BTW, I found https://github.com/microsoft/vscode/issues/80532 , and confirmed ctrl+space can trigger suggestion with "若" (tested in Mac):
![Screen Shot 2020-06-03 at 11 51 12 PM](https://user-images.githubusercontent.com/392497/83724649-7c590200-a5f5-11ea-8bb0-9840f168c18f.png)

**Comment by antfu** [comment]
That's great. Good finding!
