### ISSUE TITLE
中文”和英文}后缀匹配缺失

### ISSUE THREAD

**Issue by XiLaiTL** [antfu/wenyan-lang-vscode#23]
snippets\dynamic.json
```
"double-quote-full-width-right": {
    "prefix": [
      "”",
      "}"
    ],
    "body": [
      "」"
    ],
    "description": "」」"
```
不知道这是不是bug还是有意做如此修正。
I don't know if it is your idea to leave the single symbol.

理应该为」」而不是」

these
```
    "body": [
      "」"
    ],
```
should be
```
    "body": [
      "」」"
    ],
```

**Comment by antfu** [comment]
Can you share a snippet with the wrong highlighting? thanks

**Comment by XiLaiTL** [comment]
if you enter a ” ,there will be a single 」.
But I think it should be double .

**Comment by antfu** [comment]
Oh I see, should be a bug, do you mind to open a PR?
