### ISSUE TITLE
請問 Logo 中「文言」二字後面是什麽字？

### ISSUE THREAD

**Issue by nb5p** [antfu/wenyan-lang-vscode#3]
請問 Logo 中「文言」二字後面是什麽字？
![Logo](https://github.com/antfu/wenyan-lang-vscode/raw/master/screenshots/logo.png)

**Comment by antfu** [comment]
是VSCode的Logo 😂

**Comment by nb5p** [comment]
😅

**Comment by antfu** [comment]
如果有更好的建議也歡迎分析~謝謝
