### ISSUE TITLE
More traditional typeface in rendered SVG

### ISSUE THREAD

**Issue by edward-martyr** [antfu/wenyan-lang-vscode#4]
這個extension很好用！唯一的一點，如果排版繁體中文的話，是不是採用傳統字形（比如[一點明朝](https://github.com/ichitenfont/I.Ming)）比較好？大陸的新字形會看起來彆扭…
用戶能設置 render 字體就好了。

**Comment by antfu** [comment]
Hi~ I think this is more related to the language compiler itself. You may want to open an issue there.

Once typeface customization get supported in the compiler, I would support type selection as well.

Thanks.

**Comment by antfu** [comment]
You can also check this out https://github.com/LingDong-/wenyan-lang/issues/5

**Comment by edward-martyr** [comment]
Wow great, thanks for the notice.

**Comment by antfu** [comment]
It's solved in https://github.com/LingDong-/wenyan-lang/pull/243, closing this.
