### ISSUE TITLE
Some advice to the plugin

### ISSUE THREAD

**Issue by t-a-n-0** [antfu/wenyan-lang-vscode#5]
1. Is it possible to auto replace the full-width quotes(‘ , ’ , “ , ”) to 「 , 」 , 「「 , 」」,as Chinese input methods always input full-width symbols?
2. Is it possible to replace Chinese keywords to related syntaxes(for example,when I type "循環",it should give a list about loop operation)?It will reduce the number of changing input methods.

**Comment by antfu** [comment]
1. I have added the support in d578e0f82b4dcdc4c6ac11e59beee2df54c6baee. You can use it now in v0.7.1
2. Maybe you can modify [this file](https://github.com/antfu/wenyan-lang-vscode/blob/8556abee4877c26224b9c4a61d5ad767bbad0843/snippets/static.json) and let's see the PR and discuss.

Thanks for the advice!
