### ISSUE TITLE
新建文件未保存時，無法使用該插件

### ISSUE THREAD

**Issue by cuixiping** [antfu/wenyan-lang-vscode#9]
Ctrl+N 新建文件，文件未保存時，已將語言模式設為文言，卻無法使用該插件（插件按鈕未顯示）。
希望可以改進這點。對於寫幾句小測試，而不想保存文件的情況，特別有用。

**Comment by antfu** [comment]
That's definitely a "nice to have" feature!

But unfortunately, it's not yet supported by VSCode. Please refer to this issue https://github.com/microsoft/vscode/issues/26873

Thanks!

**Comment by cuixiping** [comment]
Can use `editorLangId`  instead of `resourceLandId`?

**Comment by antfu** [comment]
After some hack with vscode's API. I think I made it works. You can update to v0.10.1 and have a try.

**Comment by cuixiping** [comment]
👍 Awesome! Thank you.
I updated. It works as expected.
